const translations = {
    "en": {
        // Navigation & Branding
        "nav_brand": "MigrantConnect",
        "nav_services": "Services",
        "nav_resources": "Resources",
        "nav_about": "About Us",
        "nav_login": "Login",
        "nav_signup": "Sign Up",
        "partner_with_us": "Partner with Us",
        "quick_links": "Quick Links",
        "contact_info": "Contact info",
        "footer_desc": "Building a digital bridge for migrant workers to access healthcare and dignity across India.",
        "footer_copyright": "© 2026 MigrantConnect. Empowering migrant workers with transparency and care.",
        "back_to_home": "Back to home",
        "login_error_invalid": "Invalid email or password. Please try again.",
        
        // Landing Page
        "hero_title": "Empowering Journeys. Bridging Care.",
        "hero_subtitle": "Connecting migrant workers to essential health services and government welfare schemes.",
        "btn_get_connected": "Get Connected",
        "btn_learn_more": "Learn More",
        "services_title": "Comprehensive Support for Every Step",
        "service_health_title": "Health Services",
        "service_health_desc": "Instant access to your digital health records wherever you go.",
        "service_welfare_title": "Welfare Programs",
        "service_welfare_desc": "Personalized health & government welfare recommendations.",
        "service_jobs_title": "Job Opportunities",
        "service_jobs_desc": "Find verified employment prospects that respect your rights.",
        "latest_schemes": "Latest Welfare Schemes",
        "latest_schemes_desc": "Stay updated with the newest food, housing, and travel subsidies.",
        "explore_schemes": "Explore Schemes →",
        "nearby_clinics": "Nearby Health Clinics",
        "nearby_clinics_desc": "Find verified healthcare providers in your current industrial cluster.",
        "find_clinics": "Find Clinics →",
        "bridging_gap": "Bridging the Gap",
        "about_quote": "\"We believe every worker deserves dignity, health security, and access to their rights.\"",
        "about_impact_lives": "50K+",
        "about_impact_lives_label": "Lives Impacted",
        "about_impact_clinics": "1.2K+",
        "about_impact_clinics_label": "Partner Clinics",
        "about_impact_schemes": "100+",
        "about_impact_schemes_label": "Welfare Schemes",
        "hero_illustration_alt": "Platform Network Path",

        // Sign In
        "signin_pill": "Secure multi-role sign in",
        "signin_welcome": "Welcome back to your health dashboard",
        "signin_desc": "Sign in as a company admin, hospital admin, or doctor to manage records.",
        "badge_rbac": "Role-based access",
        "badge_consent": "Consent-aware",
        "badge_audit": "Audit logging",
        "activity_today": "Today’s activity",
        "live": "Live",
        "checkups": "Checkups",
        "recent_records": "New records",
        "hospitals": "Hospitals",
        "signin_illustration": "Verified healthcare bridge.",
        "login_title": "Sign in",
        "login_subtitle": "Use your registered email and password to access your portal.",
        "signup_role": "Sign in as",
        "select_role": "Select a role",
        "signup_company": "Company admin",
        "signup_hospital": "Hospital admin",
        "role_doctor": "Doctor",
        "signup_worker": "Migrant Employee",
        "login_email": "Email address",
        "login_email_placeholder": "you@example.com",
        "login_password": "Password",
        "login_password_placeholder": "Enter your password",
        "login_remember": "Keep me signed in",
        "login_forgot": "Forgot password?",
        "login_btn": "Continue",
        "divider_or": "Or",
        "login_no_account": "Create a new account",
        "signin_help": "Trouble signing in?",
        "contact_support": "Contact support",

        // Sign Up
        "signup_pill": "Create organization account",
        "signup_welcome_title": "Onboard your company or hospital",
        "signup_welcome_desc": "Choose your role and start managing employee health data.",
        "signup_badge_multi": "Multi-role signup",
        "signup_badge_profiles": "Profiles",
        "signup_badge_secure": "Secure access",
        "signup_steps_title": "What happens next?",
        "signup_step_1": "Verify your email and details.",
        "signup_step_2": "Create employee profiles.",
        "signup_step_3": "Start sharing health data.",
        "signup_illustration": "Health security network.",
        "signup_title": "Create an account",
        "signup_subtitle": "Sign up to get started.",
        "signup_error_fill": "Please fill all required fields.",
        "signup_fname": "First name",
        "signup_fname_placeholder": "John",
        "signup_lname": "Last name",
        "signup_lname_placeholder": "Doe",
        "signup_email_placeholder": "you@organization.com",
        "signup_org": "Organization name",
        "signup_org_placeholder": "Acme Corp",
        "signup_password_placeholder": "Create password",
        "signup_confirm": "Confirm password",
        "signup_confirm_placeholder": "Re-enter password",
        "signup_notes": "Additional details",
        "signup_notes_placeholder": "E.g., number of employees...",
        "signup_agree": "I agree to terms.",
        "signup_have_account": "Already registered?",
        "signup_login": "Go to sign in",
        "signup_help": "Need help?",

        // General Dashboard / Portals
        "worker_dashboard": "Worker Dashboard",
        "health_passport_verified": "Passport Verified",
        "blood_group": "Blood Group",
        "vaccination": "Vaccination",
        "verified": "Verified",
        "company_portal": "Company Portal",
        "employee_registry": "Employee registry",
        "wellness_and_consent": "Wellness & Consent",
        "analytics": "Analytics",
        "risk_overview": "Wellness Overview",
        "doctor_portal": "Doctor Portal",
        "patient_list": "Patient list",
        "audit_trail": "Audit trail",
        "compliance_admin": "Compliance Admin",
        "save_record": "Save record",
        "table_status": "Status",
        "action": "Action",
        "timestamp": "Timestamp",
        "user": "User",
        "id": "ID",
        "employee": "Employee",
        "back": "Back",
        "export_report": "Export report",
        "add_employee": "Add employee",
        "clear_form": "Clear form",
        "full_name": "Full name",
        "department": "Department",
        "partner_hospital": "Partner hospital",
        "email": "Email",
        "phone": "Phone",
        "valid_till": "Valid till",
        "granted": "Granted",
        "pending": "Pending",
        "revoked": "Revoked",
        "wellness_dashboard": "Wellness dashboard",
        "wellness_desc": "Wellness summary view.",
        "total_employees": "Total employees",
        "across_depts": "Across depts.",
        "privacy_controls": "Data controls.",
        "preferred_hospital": "Preferred hospital",
        "data_access_scope": "Scope",
        "policy_validity": "Validity",
        "add_update_policy": "Update policy",
        "compliance_reports": "Compliance reports",
        "compliance_desc": "Summaries of audits.",
        "download_demo_csv": "Download CSV",
        "doctor_onboarding": "Doctor onboarding",
        "visit_history": "Visit history",
        "save_profile": "Save profile",
        "today_schedule": "Today's schedule",
        "patients_assigned": "Patients assigned",
        "search_placeholder": "Search patients...",
        "health_record": "Health record",
        "treatment_plan": "Plan",
        "recent_records": "Recent records",
        "patient_timeline": "Patient timeline",
        "footer_advanced": "Demo medical UI.",
        "audit_summaries": "Audit summaries",
        "snapshot_desc": "Logs snapshot.",
        "audit_review": "Review workflow",
        "review_wf_desc": "Review events.",
        "update_status": "Update status",
        "save_review": "Save review",
        "reviewer_comments": "Comments",
        "events_count": "Events",
        "actor": "Actor",
        "resource": "Resource",
        "device": "Device",
        "purpose": "Purpose",
        "ai_title": "MC Assistant",
        "ai_subtitle": "Empowering Journeys",
        "ai_welcome": "Hi! I'm MC, your health assistant. How can I help you today?",
        "ai_placeholder": "Type a message or use voice...",
        "ai_error": "I'm sorry, I encountered an error."
    },
    "mr": {
        // Navigation & Branding
        "nav_brand": "मायग्रंट कनेक्ट",
        "nav_services": "सेवा",
        "nav_resources": "संसाधने",
        "nav_about": "आमच्याबद्दल",
        "nav_login": "लॉगिन",
        "nav_signup": "साइन अप",
        "partner_with_us": "आमच्याशी जोडा",
        "quick_links": "द्रुत लिंक्स",
        "contact_info": "संपर्क माहिती",
        "footer_desc": "संपूर्ण भारतात स्थलांतरित कामगारांसाठी आरोग्यसेवा आणि प्रतिष्ठा मिळवून देणारा डिजिटल पूल।",
        "footer_copyright": "© २०२६ मायग्रंट कनेक्ट. पारदर्शकता आणि काळजीसह सक्षमीकरण।",
        "back_to_home": "मुख्यपृष्ठावर परत",
        "login_error_invalid": "अवैध ईमेल किंवा पासवर्ड. कृपया पुन्हा प्रयत्न करा।",
        
        // Hero Section & index.html
        "hero_title": "सक्षम प्रवास. उत्तम काळजी.",
        "hero_subtitle": "स्थलांतरित कामगारांना आवश्यक आरोग्य सेवा आणि सरकारी कल्याणकारी योजनांशी जोडणे।",
        "btn_get_connected": "जोडले जा",
        "btn_learn_more": "अधिक जाणून घ्या",
        "services_title": "प्रत्येक टप्प्यासाठी व्यापक आधार",
        "service_health_title": "आरोग्य सेवा",
        "service_health_desc": "तुम्ही कुठेही असा, तुमच्या डिजिटल आरोग्य रेकॉर्डमध्ये त्वरित प्रवेश।",
        "service_welfare_title": "कल्याणकारी कार्यक्रम",
        "service_welfare_desc": "राज्य-विशिष्ट आणि केंद्र सरकारच्या कल्याणकारी योजनांसाठी वैयक्तिक शिफारसी।",
        "service_jobs_title": "नोकरीच्या संधी",
        "service_jobs_desc": "तुमच्या हक्कांचा आदर करणाऱ्या आणि सुरक्षित कामाची परिस्थिती देणाऱ्या सत्यापित नोकरीच्या संधी शोधा।",
        "latest_schemes": "नवीनतम कल्याणकारी योजना",
        "latest_schemes_desc": "या तिमाहीत नोंदणीकृत स्थलांतरित कामगारांसाठी उपलब्ध अन्न, गृहनिर्माण आणि प्रवास अनुदानांसह अपडेट रहा।",
        "explore_schemes": "योजना पहा →",
        "nearby_clinics": "जवळील आरोग्य केंद्रे",
        "nearby_clinics_desc": "तुमच्या सध्याच्या परिसरात सत्यापित आरोग्य सेवा प्रदाता शोधा जे मायग्रंट कनेक्ट मेडिकल पास स्वीकारतात।",
        "find_clinics": "केंद्रे शोधा →",
        "bridging_gap": "दरी कमी करणे",
        "about_quote": "\"आमचा विश्वास आहे की प्रत्येक कामगार सन्मान, आरोग्य सुरक्षा आणि त्यांच्या अधिकारांपर्यंत पोहोचण्यास पात्र आहे, मग त्यांचे काम त्यांना कुठेही नेले तरी।\"",
        "about_impact_lives": "५०K+",
        "about_impact_lives_label": "प्रभावित जीवन",
        "about_impact_clinics": "१.२K+",
        "about_impact_clinics_label": "भागीदार क्लिनिक",
        "about_impact_schemes": "१००+",
        "about_impact_schemes_label": "कल्याणकारी योजना",
        "hero_illustration_alt": "प्लॅटफॉर्म नेटवर्क पथ",

        // Sign In
        "signin_pill": "सुरक्षित मल्टी-रोल लॉगिन",
        "signin_welcome": "तुम्या आरोग्य डॅशबोर्डवर पुन्हा स्वागत आहे",
        "signin_desc": "कर्मचारी, भेटी आणि आरोग्य रेकॉर्ड व्यवस्थापित करण्यासाठी लॉगिन करा।",
        "badge_rbac": "भूमिका-आधारित प्रवेश",
        "badge_consent": "संमती-आधारित",
        "badge_audit": "ऑडिट लॉगिंग",
        "activity_today": "आजची क्रियाकलाप",
        "live": "थेट",
        "checkups": "तपासणी",
        "recent_records": "नवीन रेकॉर्ड",
        "hospitals": "रुग्णालये",
        "signin_illustration": "सत्यापित कामगारांसाठी डिजिटल आरोग्य पूल।",
        "login_title": "साइन इन करा",
        "login_subtitle": "तुमच्या पोर्टलवर जाण्यासाठी तुमचा नोंदणीकृत ईमेल आणि पासवर्ड वापरा।",
        "signup_role": "या भूमिकेत लॉगिन करा",
        "select_role": "भूमिका निवडा",
        "signup_company": "कंपनी प्रशासक",
        "signup_hospital": "रुग्णालय प्रशासक",
        "role_doctor": "डॉक्टर",
        "signup_worker": "स्थलांतरित कामगार",
        "login_email": "ईमेल पत्ता",
        "login_email_placeholder": "नाव@उदाहरण.com",
        "login_password": "पासवर्ड",
        "login_password_placeholder": "तुमचा पासवर्ड टाका",
        "login_remember": "लॉगिन ठेवा",
        "login_forgot": "पासवर्ड विसरलात?",
        "login_btn": "पुढे सुरू ठेवा",
        "divider_or": "किंवा",
        "login_no_account": "नवीन खाते तयार करा",
        "signin_help": "लॉगिन करण्यात अडचण येत आहे का?",
        "contact_support": "संपर्क साधा",

        // Sign Up
        "signup_pill": "तुमचे संस्था खाते तयार करा",
        "signup_welcome_title": "तुमची कंपनी किंवा रुग्णालय जोडा",
        "signup_welcome_desc": "तुमची भूमिका निवडा आणि कर्मचारी आरोग्य डेटा व्यवस्थापित करणे सुरू करा।",
        "signup_badge_multi": "मल्टी-रोल साइनअप",
        "signup_badge_profiles": "प्रोफाइल्स",
        "signup_badge_secure": "सुरक्षित प्रवेश",
        "signup_steps_title": "पुढे काय होईल?",
        "signup_step_1": "तुमच्या ईमेल आणि संस्थेच्या तपशीलांची पडताळणी करा।",
        "signup_step_2": "कर्मचारी प्रोफाइल तयार करा।",
        "signup_step_3": "आरोग्य डेटा शेअर करणे सुरू करा।",
        "signup_illustration": "आरोग्य सुरक्षा नेटवर्कमध्ये सामील व्हा।",
        "signup_title": "खाते तयार करा",
        "signup_subtitle": "सुरू करण्यासाठी साइन अप करा।",
        "signup_error_fill": "कृपया सर्व आवश्यक फील्ड भरा।",
        "signup_fname": "पहिले नाव",
        "signup_fname_placeholder": "राम",
        "signup_lname": "आडनाव",
        "signup_lname_placeholder": "कुमार",
        "signup_email_placeholder": "नाव@संस्था.com",
        "signup_org": "संस्थेचे नाव",
        "signup_org_placeholder": "अॅक्मे कॉर्प",
        "signup_password_placeholder": "पासवर्ड तयार करा",
        "signup_confirm": "पासवर्डची पुष्टी करा",
        "signup_confirm_placeholder": "पासवर्ड पुन्हा टाका",
        "signup_notes": "अतिरिक्त तपशील",
        "signup_notes_placeholder": "उदा. कर्मचाऱ्यांची संख्या...",
        "signup_agree": "मी अटी आणि शर्तींशी सहमत आहे।",
        "signup_have_account": "आधीच नोंदणी केली आहे का?",
        "signup_login": "लॉगिनवर जा",
        "signup_help": "मदत हवी आहे का?",

        // General Dashboard / Portals
        "worker_dashboard": "कामगार डॅशबोर्ड",
        "health_passport_verified": "आरोग्य पासपोर्ट सत्यापित",
        "blood_group": "रक्त गट",
        "vaccination": "लसीकरण",
        "verified": "सत्यापित",
        "company_portal": "कंपनी पोर्टल",
        "employee_registry": "कर्मचारी नोंदणी",
        "wellness_and_consent": "कल्याण आणि संमती",
        "analytics": "विश्लेषण",
        "risk_overview": "कल्याण विहंगावलोकन",
        "doctor_portal": "डॉक्टर पोर्टल",
        "patient_list": "रुग्णांची यादी",
        "audit_trail": "ऑडिट ट्रेल",
        "compliance_admin": "अनुपालन प्रशासन",
        "save_record": "रेकॉर्ड जतन करा",
        "table_status": "स्थिती",
        "action": "कृती",
        "timestamp": "वेळ",
        "user": "वापरकर्ता",
        "id": "आयडी",
        "employee": "कामगार",
        "back": "मागे",
        "export_report": "अहवाल निर्यात करा",
        "add_employee": "कामगार जोडा",
        "clear_form": "फॉर्म साफ करा",
        "full_name": "पूर्ण नाव",
        "department": "विभाग",
        "partner_hospital": "भागीदार रुग्णालय",
        "email": "ईमेल",
        "phone": "फोन",
        "valid_till": "पर्यंत वैध",
        "granted": "मंजूर",
        "pending": "लंबित",
        "revoked": "रद्द",
        "wellness_dashboard": "वेलनेस डॅशबोर्ड",
        "wellness_desc": "तपासणी आणि जोखीम श्रेणींचे उच्च-स्तरीय दृश्य।",
        "total_employees": "एकूण कर्मचारी",
        "across_depts": "सर्व विभागांमध्ये",
        "privacy_controls": "डेटा प्रवेश नियंत्रण।",
        "preferred_hospital": "आवडते रुग्णालय",
        "data_access_scope": "प्रवेश व्याप्ती",
        "policy_validity": "धोरण वैधता",
        "add_update_policy": "धोरण अपडेट करा",
        "compliance_reports": "अनुपालन अहवाल",
        "compliance_desc": "ऑडिट आणि प्रवेश लॉग्जचा सारांश।",
        "download_demo_csv": "CSV डाउनलोड करा",
        "doctor_onboarding": "डॉक्टर ऑनबोर्डिंग",
        "visit_history": "भेटीचा इतिहास",
        "save_profile": "प्रोफाइल जतन करा",
        "today_schedule": "आजचे वेळापत्रक",
        "patients_assigned": "नियुक्त रुग्ण",
        "search_placeholder": "रुग्ण शोधा...",
        "health_record": "आरोग्य रेकॉर्ड",
        "treatment_plan": "योजना",
        "recent_records": "अलीकडील रेकॉर्ड",
        "patient_timeline": "रुग्ण टाइमलाइन",
        "footer_advanced": "प्रगत डॉक्टर डॅशबोर्ड डेमो।",
        "audit_summaries": "ऑडिट सारांश",
        "snapshot_desc": "अलीकडील लॉग्जचा सारांश।",
        "audit_review": "पुनरावलोकन कार्यप्रवाह",
        "review_wf_desc": "ऑडिट घटनांचे पुनरावलोकन करा।",
        "update_status": "स्थिती अपडेट करा",
        "save_review": "पुनरावलोकन जतन करा",
        "reviewer_comments": "टिप्पण्या",
        "events_count": "घटनांची संख्या",
        "actor": "कर्ता",
        "resource": "संसाधन",
        "device": "डिव्हाइस",
        "purpose": "हेतू",
        "ai_title": "मायग्रंट कनेक्ट AI",
        "ai_subtitle": "सक्षम प्रवास",
        "ai_welcome": "नमस्ते! मी तुमचा आरोग्य सहाय्यक आहे. मी तुम्हाला कशी मदत करू शकतो?",
        "ai_placeholder": "तुमचा संदेश लिहा किंवा व्हॉइस वापरा...",
        "ai_error": "क्षमस्व, त्रुटी आली आहे."
    },
    "hi": {
        // Navigation & Branding
        "nav_brand": "प्रवासी-कनेक्ट",
        "nav_services": "सेवाएं",
        "nav_resources": "संसाधन",
        "nav_about": "हमारे बारे में",
        "nav_login": "लॉगिन",
        "nav_signup": "साइन अप",
        "partner_with_us": "हमारे साथ जुड़ें",
        "quick_links": "क्विक लिंक्स",
        "contact_info": "संपर्क जानकारी",
        "footer_desc": "पूरे भारत में प्रवासी श्रमिकों के लिए स्वास्थ्य सेवा और सम्मान प्रदान करने वाला डिजिटल पुल।",
        "footer_copyright": "© 2026 माइग्रेंट कनेक्ट। पारदर्शिता और देखभाल के साथ सशक्तिकरण।",
        "back_to_home": "होम पर वापस जाएं",
        "login_error_invalid": "गलत ईमेल या पासवर्ड। कृपया पुनः प्रयास करें।",
        
        // Hero Section & index.html
        "hero_title": "सशक्त यात्रा। बेहतर देखभाल।",
        "hero_subtitle": "प्रवासी श्रमिकों को आवश्यक स्वास्थ्य सेवाओं और सरकारी कल्याण योजनाओं से जोड़ना।",
        "btn_get_connected": "जुड़ें",
        "btn_learn_more": "अधिक जानें",
        "services_title": "हर कदम के लिए व्यापक सहायता",
        "service_health_title": "स्वास्थ्य सेवाएं",
        "service_health_desc": "आप जहां भी जाएं, अपने डिजिटल स्वास्थ्य रिकॉर्ड तक तुरंत पहुंच।",
        "service_welfare_title": "कल्याण कार्यक्रम",
        "service_welfare_desc": "व्यक्तिगत स्वास्थ्य और सरकारी कल्याण योजनाओं के लिए सिफारिशें।",
        "service_jobs_title": "नौकरी के अवसर",
        "service_jobs_desc": "आपके अधिकारों का सम्मान करने वाली और सुरक्षित कार्य स्थिति प्रदान करने वाली नौकरी खोजें।",
        "latest_schemes": "नवीनतम कल्याण योजनाएं",
        "latest_schemes_desc": "इस तिमाही में पंजीकृत प्रवासी श्रमिकों के लिए उपलब्ध भोजन, आवास और यात्रा सब्सिडी के साथ अपडेट रहें।",
        "explore_schemes": "योजनाएं देखें →",
        "nearby_clinics": "पास के स्वास्थ्य केंद्र",
        "nearby_clinics_desc": "अपने वर्तमान क्षेत्र में सत्यापित स्वास्थ्य सेवा प्रदाता खोजें जो माइग्रेंट कनेक्ट मेडिकल पास स्वीकार करते हैं।",
        "find_clinics": "केंद्र खोजें →",
        "bridging_gap": "खाई को पाटना",
        "about_quote": "\"हमारा मानना है कि हर श्रमिक सम्मान, स्वास्थ्य सुरक्षा और अपने अधिकारों तक पहुंच का हकदार है।\"",
        "about_impact_lives": "50K+",
        "about_impact_lives_label": "प्रवाहित जीवन",
        "about_impact_clinics": "1.2K+",
        "about_impact_clinics_label": "भागीदार क्लिनिक",
        "about_impact_schemes": "100+",
        "about_impact_schemes_label": "कल्याण योजनाएं",
        "hero_illustration_alt": "प्लैटफ़ॉर्म नेटवर्क पथ",

        // Sign In
        "signin_pill": "सुरक्षित मल्टी-रोल लॉगिन",
        "signin_welcome": "आपके स्वास्थ्य डैशबोर्ड पर वापसी पर स्वागत है",
        "signin_desc": "कर्मचारियों, नियुक्तियों और स्वास्थ्य रिकॉर्ड को प्रबंधित करने के लिए लॉगिन करें।",
        "badge_rbac": "भूमिका-आधारित पहुंच",
        "badge_consent": "सहमति-आधारित",
        "badge_audit": "ऑडिट लॉगिंग",
        "activity_today": "आज की गतिविधि",
        "live": "लाइव",
        "checkups": "जांच",
        "recent_records": "नए रिकॉर्ड",
        "hospitals": "अस्पताल",
        "signin_illustration": "डिजिटल स्वास्थ्य पुल।",
        "login_title": "साइन इन करें",
        "login_subtitle": "अपने पोर्टल तक पहुंचने के लिए अपने पंजीकृत ईमेल और पासवर्ड का उपयोग करें।",
        "signup_role": "इस भूमिका में लॉगिन करें",
        "select_role": "भूमिका चुनें",
        "signup_company": "कंपनी व्यवस्थापक",
        "signup_hospital": "अस्पताल व्यवस्थापक",
        "role_doctor": "डॉक्टर",
        "signup_worker": "प्रवासी श्रमिक",
        "login_email": "ईमेल पता",
        "login_email_placeholder": "नाम@उदाहरण.com",
        "login_password": "पासवर्ड",
        "login_password_placeholder": "अपना पासवर्ड डालें",
        "login_remember": "लॉगिन रखें",
        "login_forgot": "पासवर्ड भूल गए?",
        "login_btn": "जारी रखें",
        "divider_or": "या",
        "login_no_account": "नया खाता बनाएं",
        "signin_help": "लॉगिन करने में समस्या?",
        "contact_support": "संपर्क करें",

        // Sign Up
        "signup_pill": "अपना संगठन खाता बनाएं",
        "signup_welcome_title": "अपनी कंपनी या अस्पताल जोड़ें",
        "signup_welcome_desc": "अपनी भूमिका चुनें और कर्मचारी स्वास्थ्य डेटा प्रबंधित करना शुरू करें।",
        "signup_badge_multi": "मल्टी-रोल साइनअप",
        "signup_badge_profiles": "प्रोफाइल",
        "signup_badge_secure": "सुरक्षित पहुंच",
        "signup_steps_title": "आगे क्या होगा?",
        "signup_step_1": "अपने ईमेल और विवरण सत्यापित करें।",
        "signup_step_2": "कर्मचारी प्रोफाइल बनाएं।",
        "signup_step_3": "स्वास्थ्य डेटा साझा करना शुरू करें।",
        "signup_illustration": "स्वास्थ्य सुरक्षा नेटवर्क में शामिल हों।",
        "signup_title": "खाता बनाएं",
        "signup_subtitle": "शुरू करने के लिए साइन अप करें।",
        "signup_error_fill": "कृपया सभी आवश्यक फ़ील्ड भरें।",
        "signup_fname": "प्रथम नाम",
        "signup_fname_placeholder": "राम",
        "signup_lname": "अंतिम नाम",
        "signup_lname_placeholder": "कुमार",
        "signup_email_placeholder": "नाम@संगठन.com",
        "signup_org": "संगठन का नाम",
        "signup_org_placeholder": "एक्मे कॉर्प",
        "signup_password_placeholder": "पासवर्ड बनाएं",
        "signup_confirm": "पासवर्ड की पुष्टि करें",
        "signup_confirm_placeholder": "पासवर्ड फिर से डालें",
        "signup_notes": "अतिरिक्त विवरण",
        "signup_notes_placeholder": "उदा. कर्मचारियों की संख्या...",
        "signup_agree": "मैं शर्तों से सहमत हूं।",
        "signup_have_account": "पहले से पंजीकृत हैं?",
        "signup_login": "लॉगिन पर जाएं",
        "signup_help": "मदद चाहिए?",

        // General Dashboard / Portals
        "worker_dashboard": "श्रमिक डैशबोर्ड",
        "health_passport_verified": "स्वास्थ्य पासपोर्ट सत्यापित",
        "blood_group": "रक्त समूह",
        "vaccination": "टीकाकरण",
        "verified": "सत्यापित",
        "company_portal": "कंपनी पोर्टल",
        "employee_registry": "कर्मचारी रजिस्ट्री",
        "wellness_and_consent": "कल्याण और सहमति",
        "analytics": "एनालिटिक्स",
        "risk_overview": "कल्याण विहंगावलोकन",
        "doctor_portal": "डॉक्टर पोर्टल",
        "patient_list": "रोगियों की सूची",
        "audit_trail": "ऑडिट ट्रेल",
        "compliance_admin": "अनुपालन प्रशासन",
        "save_record": "रिकॉर्ड सहेजें",
        "table_status": "स्थिति",
        "action": "कार्रवाई",
        "timestamp": "समय",
        "user": "उपयोगकर्ता",
        "id": "आईडी",
        "employee": "श्रमिक",
        "back": "पीछे",
        "export_report": "रिपोर्ट निर्यात करें",
        "add_employee": "श्रमिक जोड़ें",
        "clear_form": "फॉर्म साफ करें",
        "full_name": "पूरा नाम",
        "department": "विभाग",
        "partner_hospital": "भागीदार अस्पताल",
        "email": "ईमेल",
        "phone": "फ़ोन",
        "valid_till": "तक वैध",
        "granted": "अनुमत",
        "pending": "लंबित",
        "revoked": "निरस्त",
        "wellness_dashboard": "वेलनेस डैशबोर्ड",
        "wellness_desc": "कल्याण सारांश दृश्य।",
        "total_employees": "कुल श्रमिक",
        "across_depts": "सभी विभागों में",
        "privacy_controls": "डेटा नियंत्रण।",
        "preferred_hospital": "पसंदीदा अस्पताल",
        "data_access_scope": "कार्यक्षेत्र",
        "policy_validity": "वैधता",
        "add_update_policy": "पॉलिसी अपडेट करें",
        "compliance_reports": "अनुपालन रिपोर्ट",
        "compliance_desc": "ऑडिट का सारांश।",
        "download_demo_csv": "CSV डाउनलोड करें",
        "doctor_onboarding": "डॉक्टर ऑनबोर्डिंग",
        "visit_history": "विजिट इतिहास",
        "save_profile": "प्रोफाइल सहेजें",
        "today_schedule": "आज का शेड्यूल",
        "patients_assigned": "नियुक्त रोगी",
        "search_placeholder": "रोगी खोजें...",
        "health_record": "स्वास्थ्य रिकॉर्ड",
        "treatment_plan": "योजना",
        "recent_records": "हाल के रिकॉर्ड",
        "patient_timeline": "रोगी टाइमलाइन",
        "footer_advanced": "प्रगत डॉक्टर डैशबोर्ड डेमो।",
        "audit_summaries": "ऑडिट सारांश",
        "snapshot_desc": "लॉग्ज का सारांश।",
        "audit_review": "समीक्षा कार्यप्रवाह",
        "review_wf_desc": "घटनाओं की समीक्षा करें।",
        "update_status": "स्थिति अपडेट करें",
        "save_review": "समीक्षा सहेजें",
        "reviewer_comments": "टिप्पणियां",
        "events_count": "घटनाओं की संख्या",
        "actor": "कर्ता",
        "resource": "संसाधन",
        "device": "उपकरण",
        "purpose": "उद्देश्य",
        "ai_title": "प्रवासी-कनेক্ট AI",
        "ai_subtitle": "सशक्त यात्रा",
        "ai_welcome": "नमस्ते! मैं आपका स्वास्थ्य सहायक हूँ। मैं आपकी कैसे मदद कर सकता हूँ?",
        "ai_placeholder": "अपना संदेश लिखें या वॉयस का उपयोग करें...",
        "ai_error": "क्षमा करें, त्रुटि हुई है।"
    },
    "bn": {
        // Navigation & Branding
        "nav_brand": "মাইগ্র্যান্ট কানেক্ট",
        "nav_services": "পরিষেবা",
        "nav_resources": "সম্পদ",
        "nav_about": "আমাদের সম্পর্কে",
        "nav_login": "লগইন",
        "nav_signup": "সাইন আপ",
        "partner_with_us": "আমাদের সাথে যুক্ত হন",
        "quick_links": "কুইক লিঙ্ক",
        "contact_info": "যোগাযোগের তথ্য",
        "footer_desc": "পুরো ভারতে পরিযায়ী শ্রমিকদের জন্য স্বাস্থ্যসেবা এবং মর্যাদা প্রদানের ডিজিটাল সেতু।",
        "footer_copyright": "© 2026 মাইগ্র্যান্ট কানেক্ট। স্বচ্ছতা এবং যত্নের সাথে ক্ষমতায়ন।",
        "back_to_home": "হোমে ফিরে যান",
        "login_error_invalid": "ভুল ইমেল বা পাসওয়ার্ড। দয়া করে আবার চেষ্টা করুন।",
        
        // Hero Section & index.html
        "hero_title": "ক্ষমতায়ন যাত্রা। উন্নত সেবা।",
        "hero_subtitle": "পরিযায়ী শ্রমিকদের প্রয়োজনীয় স্বাস্থ্য পরিষেবা এবং সরকারি কল্যাণ প্রকল্পের সাথে যুক্ত করা।",
        "btn_get_connected": "যুক্ত হন",
        "btn_learn_more": "আরও জানুন",
        "services_title": "প্রতিটি পদক্ষেপের জন্য ব্যাপক সহায়তা",
        "service_health_title": "স্বাস্থ্য পরিষেবা",
        "service_health_desc": "আপনি যেখানেই যান না কেন আপনার ডিজিটাল স্বাস্থ্য রেকর্ডে তাত্ক্ষণিক অ্যাক্সেস।",
        "service_welfare_title": "কল্যাণমূলক প্রোগ্রাম",
        "service_welfare_desc": "ব্যক্তিগত স্বাস্থ্য এবং সরকারি কল্যাণ প্রকল্পের জন্য সুপারিশ।",
        "service_jobs_title": "চাকরির সুযোগ",
        "service_jobs_desc": "আপনার অধিকারকে সম্মান করে এমন যাচাইকৃত চাকরির সুযোগ খুঁজুন।",
        "latest_schemes": "সাম্প্রতিক কল্যাণমূলক প্রকল্প",
        "latest_schemes_desc": "এই ত্রৈমাসিক নিবন্ধিত পরিযায়ী শ্রমিকদের জন্য উপলব্ধ সাহায্য পান।",
        "explore_schemes": "প্রকল্পগুলি দেখুন →",
        "nearby_clinics": "কাছাকাছি স্বাস্থ্য কেন্দ্র",
        "nearby_clinics_desc": "আপনার বর্তমান অঞ্চলে যাচাইকৃত স্বাস্থ্যসেবা প্রদানকারী খুঁজুন।",
        "find_clinics": "কেন্দ্র খুঁজুন →",
        "bridging_gap": "ব্যবধান ঘুচানো",
        "about_quote": "\"আমরা বিশ্বাস করি প্রতিটি শ্রমিক মর্যাদা, স্বাস্থ্য সুরক্ষা এবং অধিকার পাওয়ার দাবিদার।\"",
        "about_impact_lives": "50K+",
        "about_impact_lives_label": "প্রভাবিত জীবন",
        "about_impact_clinics": "1.2K+",
        "about_impact_clinics_label": "অংশীদার ক্লিনিক",
        "about_impact_schemes": "100+",
        "about_impact_schemes_label": "কল্যাণ প্রকল্প",
        "hero_illustration_alt": "প্ল্যাটফর্ম নেটওয়ার্ক পথ",

        // Sign In
        "signin_pill": "সুরক্ষিত মাল্টি-রোল লগইন",
        "signin_welcome": "আপনার স্বাস্থ্য ড্যাশবোর্ডে স্বাগতম",
        "signin_desc": "কর্মী, অ্যাপয়েন্টমেন্ট এবং স্বাস্থ্য রেকর্ড পরিচালনা করতে লগইন করুন।",
        "badge_rbac": "ভূমিকা-ভিত্তিক অ্যাক্সেস",
        "badge_consent": "সম্মতি-ভিত্তিক",
        "badge_audit": "অডিট লগিং",
        "activity_today": "আজকের কার্যকলাপ",
        "live": "লাইভ",
        "recent_records": "নতুন রেকর্ড",
        "hospitals": "হাসপাতাল",
        "login_title": "সাইন ইন করুন",
        "login_email": "ইমেল ঠিকানা",
        "login_password": "পাসওয়ার্ড",
        "login_btn": "চালিয়ে যান",
        "ai_title": "মাইগ্র্যান্ট কানেক্ট AI",
        "ai_subtitle": "ক্ষমতায়ন যাত্রা",
        "ai_welcome": "নমস্কার! আমি আপনার স্বাস্থ্য সহকারী। আমি আপনাকে কীভাবে সাহায্য করতে পারি?",
        "ai_placeholder": "আপনার বার্তা লিখুন বা ভয়েস ব্যবহার করুন...",
        "ai_error": "দুঃখিত, একটি ত্রুটি হয়েছে।"
    },
    "te": {
        // Navigation & Branding
        "nav_brand": "మైగ్రెంట్ కనెక్ట్",
        "nav_services": "సేవలు",
        "nav_resources": "వనరులు",
        "nav_about": "మా గురించి",
        "nav_login": "లాగిన్",
        "nav_signup": "సైన్ అప్",
        "partner_with_us": "మాతో భాగస్వామి అవ్వండి",
        "quick_links": "త్వరిత లింకులు",
        "contact_info": "సంప్రదింపు సమాచారం",
        "footer_desc": "భారతదేశం అంతటా వలస కార్మికులకు ఆరోగ్య సంరక్షణ మరియు గౌరవాన్ని అందించే డిజిటల్ వంతెన.",
        "footer_copyright": "© 2026 మైగ్రెంట్ కనెక్ట్. పారదర్శకత మరియు సంరక్షణతో సాధికారత.",
        "back_to_home": "హోమ్‌కు తిరిగి వెళ్ళు",
        "login_error_invalid": "చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్. దయచేసి మళ్ళీ ప్రయత్నించండి.",
        
        // Hero Section & index.html
        "hero_title": "సాధికారత ప్రయాణం. మెరుగైన సంరక్షణ.",
        "hero_subtitle": "వలస కార్మికులను అవసరమైన ఆరోగ్య సేవలు మరియు ప్రభుత్వ సంక్షేమ పథకాలతో అనుసంధానించడం.",
        "btn_get_connected": "కనెక్ట్ అవ్వండి",
        "btn_learn_more": "మరింత తెలుసుకోండి",
        "services_title": "ప్రతి అడుగులోనూ సమగ్ర మద్దతు",
        "service_health_title": "ఆరోగ్య సేవలు",
        "service_health_desc": "మీరు ఎక్కడికి వెళ్లినా మీ డిజిటల్ ఆరోగ్య రికార్డులకు తక్షణ ప్రాప్యత.",
        "service_welfare_title": "సంక్షేమ కార్యక్రమాలు",
        "service_welfare_desc": "వ్యక్తిగత ఆరోగ్య మరియు ప్రభుత్వ సంక్షేమ పథకాల సిఫార్సులు.",
        "service_jobs_title": "ఉద్యోగ అవకాశాలు",
        "service_jobs_desc": "మీ హక్కులను గౌరవించే మరియు సురక్షితమైన పని పరిస్థితులను అందించే ఉద్యోగాలను కనుగొనండి.",
        "latest_schemes": "తాజా సంక్షేమ పథకాలు",
        "explore_schemes": "పథకాలను అన్వేషించండి →",
        "nearby_clinics": "సమీప ఆరోగ్య కేంద్రాలు",
        "find_clinics": "కేంద్రాలను కనుగొనండి →",
        "bridging_gap": "దూరాన్ని తగ్గించడం",
        "about_impact_lives": "50K+",
        "about_impact_lives_label": "ప్రభావితమైన వ్యక్తులు",
        "about_impact_clinics": "1.2K+",
        "about_impact_clinics_label": "భాగస్వామ్య క్లినిక్‌లు",
        "about_impact_schemes": "100+",
        "about_impact_schemes_label": "సంక్షేమ పథకాలు",

        // Sign In
        "signin_pill": "సురక్షిత మల్టీ-రోల్ లాగిన్",
        "signin_welcome": "మీ ఆరోగ్య డ్యాష్‌బోర్డ్‌కు స్వాగతం",
        "login_title": "సైన్ ఇన్ చేయండి",
        "login_email": "ఇమెయిల్ చిరునామా",
        "login_password": "పాస్‌వర్డ్",
        "login_btn": "కొనసాగించు",
        "ai_title": "మైగ్రెంట్ కనెక్ట్ AI",
        "ai_subtitle": "సాధికారత ప్రయాణం",
        "ai_welcome": "నమస్తే! నేను మీ ఆరోగ్య సహాయకుడిని. నేను మీకు ఎలా సహాయపడగలను?",
        "ai_placeholder": "మీ సందేశాన్ని టైప్ చేయండి లేదా వాయిస్ ఉపయోగించండి...",
        "ai_error": "క్షమించండి, లోపం సంభవించింది."
    }
};

function translatePage() {
    const lang = localStorage.getItem('language') || 'en';
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[lang] && translations[lang][key]) {
            el.placeholder = translations[lang][key];
        }
    });
    document.querySelectorAll('[data-i18n-alt]').forEach(el => {
        const key = el.getAttribute('data-i18n-alt');
        if (translations[lang] && translations[lang][key]) {
            el.alt = translations[lang][key];
        }
    });
}

function injectSelector() {
    if (document.getElementById('lang-select')) return;
    const selectorHTML = `
        <div class="fixed bottom-6 left-6 z-[100]">
            <div class="bg-white/80 backdrop-blur-md p-1.5 rounded-2xl shadow-2xl border border-white/20 flex items-center space-x-1">
                <select id="lang-select" class="bg-transparent border-none focus:ring-0 text-sm font-bold text-slate-800 pr-8 cursor-pointer rounded-xl">
                    <option value="en">English (Global)</option>
                    <option value="hi">हिन्दी (Hindi)</option>
                    <option value="bn">বাংলা (Bengali)</option>
                    <option value="mr">मराठी (Marathi)</option>
                    <option value="te">తెలుగు (Telugu)</option>
                </select>
            </div>
        </div>
    `;
    const div = document.createElement('div');
    div.id = 'lang-selector-parent';
    div.innerHTML = selectorHTML;
    document.body.appendChild(div);
    const select = document.getElementById('lang-select');
    select.value = localStorage.getItem('language') || 'en';
    select.addEventListener('change', (e) => {
        localStorage.setItem('language', e.target.value);
        translatePage();
        window.dispatchEvent(new CustomEvent('languageChanged', { detail: e.target.value }));
    });
}

document.addEventListener('DOMContentLoaded', () => {
    injectSelector();
    translatePage();
});
